version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      SERVICES: sqs,ssm,secretsmanager
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - localstack-data:/var/lib/localstack

  init-localstack:
    image: amazon/aws-cli:2.15.20
    depends_on:
      - localstack
    entrypoint: >
      /bin/sh -c "
      aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name todo-events &&
      echo 'SQS queue todo-events created in LocalStack'
      "
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo-sqlserver
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ford123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Ford123!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  todo-api:
    build: .
    container_name: todo-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      DB_HOST: "sqlserver"
      DB_NAME: "todo_db"
      DB_USER: "sa"
      DB_PASSWORD: "Ford123!"
    ports:
      - "8080:8080"

volumes:
  mssql-data: {}
  localstack-data: {}
